name: chart-ccd-def-cleanup pipeline
trigger:
  branches:
    include:
    - refs/tags/*
pr:
  branches:
    include:
    - master
resources:
  repositories:
  - repository: cnp-azuredevops-libraries
    type: github
    ref: refs/heads/master
    name: hmcts/cnp-azuredevops-libraries
    endpoint: 'hmcts'

variables:
  - name: agentPool
    value: ubuntu-latest

jobs:
- job: Validate
  pool:
    vmImage: ${{ variables.agentPool }}
  steps:
  - template: steps/charts/validate.yaml@cnp-azuredevops-libraries
    parameters:
      chartName: ccd-def-cleanup
      chartReleaseName: chart-ccd-def-cleanup-ci-test
      chartNamespace: chart-tests
      helmInstallTimeout: "300"

- job: Release
  # Make sure we have a tag to run this job
  condition: >
    and(
        succeeded(),
        startsWith(variables['Build.SourceBranch'], 'refs/tags/')
      )
  dependsOn: Validate
  pool:
    vmImage: ${{ variables.agentPool }}
  steps:
  - template: steps/charts/release.yaml@cnp-azuredevops-libraries
    parameters:
      chartName: ccd-def-cleanup
      chartReleaseName: chart-ccd-def-cleanup
      chartNamespace: chart-tests
