api:
  ccdDefStore: "https://ccd-definition-store-sscs-tribunals-api-pr-3977.preview.platform.hmcts.net"
  ccdDataStore: "https://ccd-data-store-api-sscs-tribunals-api-pr-3977.preview.platform.hmcts.net"
image: hmctspublic.azurecr.io/imported/curlimages/curl:7.85.0

memoryRequests: 128Mi
cpuRequests: 250m
memoryLimits: 1G
cpuLimits: 1
ttlSecondsAfterFinished: 3600 #1hr
debug: false
posthook: post-delete
prehook: pre-delete
